# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kernel_pb2 as kernel__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kernel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KernelServiceStub(object):
    """--- CORE KERNEL INTERFACE ---
    The KernelService is the primary entry point for orchestrating LLM "ALUs".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/ank.v1.KernelService/SubmitTask',
                request_serializer=kernel__pb2.TaskRequest.SerializeToString,
                response_deserializer=kernel__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.WatchTask = channel.unary_stream(
                '/ank.v1.KernelService/WatchTask',
                request_serializer=kernel__pb2.TaskSubscription.SerializeToString,
                response_deserializer=kernel__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/ank.v1.KernelService/GetSystemStatus',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.SystemStatus.FromString,
                _registered_method=True)
        self.ListProcesses = channel.unary_unary(
                '/ank.v1.KernelService/ListProcesses',
                request_serializer=kernel__pb2.Empty.SerializeToString,
                response_deserializer=kernel__pb2.ProcessList.FromString,
                _registered_method=True)
        self.TeleportProcess = channel.unary_stream(
                '/ank.v1.KernelService/TeleportProcess',
                request_serializer=kernel__pb2.PCB.SerializeToString,
                response_deserializer=kernel__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.InitializeMasterAdmin = channel.unary_unary(
                '/ank.v1.KernelService/InitializeMasterAdmin',
                request_serializer=kernel__pb2.AdminSetupRequest.SerializeToString,
                response_deserializer=kernel__pb2.AdminSetupResponse.FromString,
                _registered_method=True)
        self.CreateTenant = channel.unary_unary(
                '/ank.v1.KernelService/CreateTenant',
                request_serializer=kernel__pb2.TenantCreateRequest.SerializeToString,
                response_deserializer=kernel__pb2.TenantCreateResponse.FromString,
                _registered_method=True)
        self.ConfigureEngine = channel.unary_unary(
                '/ank.v1.KernelService/ConfigureEngine',
                request_serializer=kernel__pb2.EngineConfigRequest.SerializeToString,
                response_deserializer=kernel__pb2.Empty.FromString,
                _registered_method=True)


class KernelServiceServicer(object):
    """--- CORE KERNEL INTERFACE ---
    The KernelService is the primary entry point for orchestrating LLM "ALUs".
    """

    def SubmitTask(self, request, context):
        """Submits a new mission to the Kernel. Returns a PID (Process ID).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTask(self, request, context):
        """Real-time stream of the process execution (Thinking, Syscalls, Results).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Returns detailed information about the Kernel's health and hardware usage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProcesses(self, request, context):
        """Lists all active processes in the Kernel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TeleportProcess(self, request, context):
        """Teleports a full process. The Worker adds it to its local Scheduler.
        The stream returns real-time state changes (RUNNING, WAITING).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeMasterAdmin(self, request, context):
        """--- IDENTITY & TENANT MANAGEMENT ---
        Initializes the super admin if not yet configured
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTenant(self, request, context):
        """Generates a new tenant, assigns port and temporary passphrase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureEngine(self, request, context):
        """Forces a password reset for a given tenant
        Configures the Cognitive Engine dynamically
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=kernel__pb2.TaskRequest.FromString,
                    response_serializer=kernel__pb2.TaskResponse.SerializeToString,
            ),
            'WatchTask': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchTask,
                    request_deserializer=kernel__pb2.TaskSubscription.FromString,
                    response_serializer=kernel__pb2.TaskEvent.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.SystemStatus.SerializeToString,
            ),
            'ListProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProcesses,
                    request_deserializer=kernel__pb2.Empty.FromString,
                    response_serializer=kernel__pb2.ProcessList.SerializeToString,
            ),
            'TeleportProcess': grpc.unary_stream_rpc_method_handler(
                    servicer.TeleportProcess,
                    request_deserializer=kernel__pb2.PCB.FromString,
                    response_serializer=kernel__pb2.TaskEvent.SerializeToString,
            ),
            'InitializeMasterAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeMasterAdmin,
                    request_deserializer=kernel__pb2.AdminSetupRequest.FromString,
                    response_serializer=kernel__pb2.AdminSetupResponse.SerializeToString,
            ),
            'CreateTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTenant,
                    request_deserializer=kernel__pb2.TenantCreateRequest.FromString,
                    response_serializer=kernel__pb2.TenantCreateResponse.SerializeToString,
            ),
            'ConfigureEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureEngine,
                    request_deserializer=kernel__pb2.EngineConfigRequest.FromString,
                    response_serializer=kernel__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ank.v1.KernelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ank.v1.KernelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KernelService(object):
    """--- CORE KERNEL INTERFACE ---
    The KernelService is the primary entry point for orchestrating LLM "ALUs".
    """

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ank.v1.KernelService/SubmitTask',
            kernel__pb2.TaskRequest.SerializeToString,
            kernel__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ank.v1.KernelService/WatchTask',
            kernel__pb2.TaskSubscription.SerializeToString,
            kernel__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ank.v1.KernelService/GetSystemStatus',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ank.v1.KernelService/ListProcesses',
            kernel__pb2.Empty.SerializeToString,
            kernel__pb2.ProcessList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TeleportProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ank.v1.KernelService/TeleportProcess',
            kernel__pb2.PCB.SerializeToString,
            kernel__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeMasterAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ank.v1.KernelService/InitializeMasterAdmin',
            kernel__pb2.AdminSetupRequest.SerializeToString,
            kernel__pb2.AdminSetupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ank.v1.KernelService/CreateTenant',
            kernel__pb2.TenantCreateRequest.SerializeToString,
            kernel__pb2.TenantCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ank.v1.KernelService/ConfigureEngine',
            kernel__pb2.EngineConfigRequest.SerializeToString,
            kernel__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
