# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: siren.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'siren.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsiren.proto\x12\x0c\x61nk.v1.siren\"X\n\nAudioChunk\x12\x17\n\x0fsequence_number\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\x12\x13\n\x0bsample_rate\x18\x04 \x01(\r\"T\n\nSirenEvent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\x19processed_sequence_number\x18\x03 \x01(\x04\x32U\n\x0cSirenService\x12\x45\n\x0bSirenStream\x12\x18.ank.v1.siren.AudioChunk\x1a\x18.ank.v1.siren.SirenEvent(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'siren_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=29
  _globals['_AUDIOCHUNK']._serialized_end=117
  _globals['_SIRENEVENT']._serialized_start=119
  _globals['_SIRENEVENT']._serialized_end=203
  _globals['_SIRENSERVICE']._serialized_start=205
  _globals['_SIRENSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
