# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import siren_pb2 as siren__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in siren_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SirenServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SirenStream = channel.stream_stream(
                '/ank.v1.siren.SirenService/SirenStream',
                request_serializer=siren__pb2.AudioChunk.SerializeToString,
                response_deserializer=siren__pb2.SirenEvent.FromString,
                _registered_method=True)


class SirenServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SirenStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SirenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SirenStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SirenStream,
                    request_deserializer=siren__pb2.AudioChunk.FromString,
                    response_serializer=siren__pb2.SirenEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ank.v1.siren.SirenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ank.v1.siren.SirenService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SirenService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SirenStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ank.v1.siren.SirenService/SirenStream',
            siren__pb2.AudioChunk.SerializeToString,
            siren__pb2.SirenEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
